### ISSUE TITLE
Jenkins Manager does not seem to work with VS2013 Update 4?

### ISSUE THREAD

**Issue by MartinLemburg** [tomkuijsten/vsjenkinsmanager#31]
After updating VS2013 to Update 4, I reentered and applied the settings and now the Jenkins Manager doesn't seem to work anymore. It seems to get stuck:

>![The tool window](https://farm8.staticflickr.com/7486/15896159452_51f898229a.jpg)

The output window only contains `Jenkins Manager loaded`. Even after enabling debug output.

**Comment by tomkuijsten** [comment]
Can't reproduce the error anymore.
