### ISSUE TITLE
Unable to add new server

### ISSUE THREAD

**Issue by DominikF-KEB** [tomkuijsten/vsjenkinsmanager#32]
Hi,

I found the Jenkins manager in the AddIn gallery and thought it could be interesting for us and installed it for a test. But when I want to add a new server in the options. it always rejects the server URL with a red border and a tooltip saying "Url is not a valid Jenkins server."
The Url in our intranet uses an IP adress and a port (e.g.: http://10.20.30.40:8080/jenkins), but I don't think that this is the problem, because it also rejects any other URL which I insert (even the sample Url www.server.com/alm/jenkins) with the same error message.
Do you have any Idea, what I'm doing wrong?
For your information: I use Visual Studio 2013 Professional, Update 4 on Win7 x64.

**Comment by tomkuijsten** [comment]
The url is fetched and it should contain a header with the Jenkins version. Could you check the headers (using fiddler, or IE/Chrome developer tools) of your url?

**Comment by DominikF-KEB** [comment]
Hi,

Thanks for your reply.
I already downloaded your sources last week and debugged the Connection. The exception says "The Operation has timed out"
Obviously the Problem is located in the Network configuration here (maybe Proxy Settings etc). Strange thing is, that I'm able to access Jenkins with firefox and Internet Explorer without any Problem from the same Computer.
Probably the fault is not on your side, sorry for the inconvenience.



Mit freundlichen Grüßen / Best regards,


-----Tom Kuijsten <notifications@github.com> schrieb: ----- 
An: tomkuijsten/vsjenkinsmanager <vsjenkinsmanager@noreply.github.com>
Von: Tom Kuijsten <notifications@github.com>
Datum: 03.01.2015 09:59
Kopie: DominikF-KEB <dominik.follmann@keb.de>
Betreff: Re: [vsjenkinsmanager] Unable to add new server (#32)


The url is fetched and it should contain a header with the Jenkins version. Could you check the headers (using fiddler, or IE/Chrome developer tools) of your url?
&#8212;
Reply to this email directly or view it on GitHub.
i. A. Dipl.-Ing./M. Sc.   Dominik Follmann
 Softwarearchitekt - Software Architect
 - ENTWICKLUNG ELEKTRONIK - ANWENDUNGSSOFTWARE / R&D ELECTRONICS - APPLICATION SOFTWARE -

Phone: +49 5263 401-867
Telefax: +49 5263 401-402
 
Dominik.Follmann@KEB.de




Karl E. Brinkmann GmbH  |  Foersterweg 36 - 38  |  32683 Barntrup / Germany
Phone: +49 5263 401-0  |  Telefax: +49 5263 401-116
WEB: www.KEB.de  |  E-Mail: Info@KEB.de

Geschaeftsfuehrer / Directors: Thomas Brinkmann, Ralf Lutter, Vittorio Tavella, 
Wolfgang Wiele
Sitz der Gesellschaft / Registered office: 32683 Barntrup - Ust-Id.Nr. 
DE811173380
Amtsgericht / District Court: Lemgo - HRB 5105

KEB Newsletter - Immer gut informiert sein! - Always well-informed!
www.keb.de/de/newsletter | www.keb.de/en/newsletter


Diese E-Mail enthaelt moeglicherweise vertrauliche und / oder rechtlich 
geschuetzte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese 
E-Mail irrtuemlich erhalten haben, informieren Sie bitte sofort den Absender 
und vernichten diese E-Mail. Das unerlaubte Kopieren sowie die unbefugte 
Weitergabe dieser E-Mail ist nicht gestattet.
This e-mail may contain confidential and / or privileged information. If you 
are not the intended recipient (or have received this e-mail in error) please 
notify the sender immediately and destroy this e-mail. Any unauthorised 
copying, disclosure or distribution of the material in this e-mail is strictly 
forbidden.

**Comment by tomkuijsten** [comment]
No problem at all. If you can access it with a browser, VS (thus the Jenkins manager plugin) should be able to do the same. Let me know when it seems a problem at my end anyway. You can close the issue when your sure it's an environment problem.
