### ISSUE TITLE
Automatically kick off build on TFS checkin

### ISSUE THREAD

**Issue by bmstambaugh** [tomkuijsten/vsjenkinsmanager#33]
It would be nice if a build could automatically be triggered when a check in is done to a project in TFS. Using the "Link to current solution" option and then subscribing to an event in TFS could trigger the "Build now"  event.

So more information around subscribing to events in TFS...
http://msdn.microsoft.com/en-us/magazine/cc507647.aspx#S3

**Comment by tomkuijsten** [comment]
I understand the need for you for such a functionality, but I'm not sure if a visual studio plugin is the best place for it. Would be cleaner if TFS could call an url when something is commited, don't you agree?

**Comment by bmstambaugh** [comment]
Agreed.  Thanks
