### ISSUE TITLE
Does not work in VS2012

### ISSUE THREAD

**Issue by oliverweiss** [tomkuijsten/vsjenkinsmanager#37]
Hi, It seems that a reference version is not correct for VS2012 (V11.0)

Below is an extract of ActivityLog.xml regarding the loading of the plugin:

  <entry>
    <record>1092</record>
    <time>2015/06/11 14:16:13.814</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>CreateInstance failed for package [VSJenkinsManagerPackage]</description>
    <guid>{252D354D-9787-42B0-B5CC-6B14E08F160F}</guid>
    <hr>80070002</hr>
    <errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.Shell.12.0, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.</errorinfo>
  </entry>

**Comment by tomkuijsten** [comment]
Thanks for the report, I'll take a look at it.

**Comment by tomkuijsten** [comment]
V1.0.0.5 released and should work with VS2012, can you confirm this Oliver?

**Comment by oliverweiss** [comment]
Hi Tom,
Thanks, works fine now!

Olivier

Le mer. 17 juin 2015 à 14:54, Tom Kuijsten <notifications@github.com> a
écrit :

**Comment by tomkuijsten** [comment]
Np, thanks for the feedback.
