### ISSUE TITLE
ÖÜÄ is not shown correct

### ISSUE THREAD

**Issue by reaction1989** [tomkuijsten/vsjenkinsmanager#39]
If you have an Umlaut in your Jenkins job then it tends to not display it correctly in your plugin.

**Comment by tomkuijsten** [comment]
Could you test if the json api does return it in the correct format? If it doesn't, I can't do much to fix it.

**Comment by reaction1989** [comment]
I tested it with the JSON-Api and the umlaute are correct.

**Comment by tomkuijsten** [comment]
Ok, I'll see if I can find the problem. Thanks for the report.

**Comment by reaction1989** [comment]
Fixed it in following PullRequest#45

**Comment by tomkuijsten** [comment]
Fixed with #45
